name: Publish package to the Maven Central Repository
on:
  release:
    types: [ published ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
#       - name: Import GPG Key
#         uses: crazy-max/ghaction-import-gpg@v5
#         with:
#           gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
#           passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
          server-id: github
#           server-username: MAVEN_USERNAME
#           server-password: MAVEN_PASSWORD

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#
#       - name: Publish package
#         run: mvn --batch-mode deploy
#         env:
#           MAVEN_USERNAME: kimsoungryoul
#           MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}